# Generated by Django 2.2.3 on 2019-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190916_1214'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='review_later',
            field=models.ManyToManyField(blank=True, related_name='review_later', to='reviews.MovieReview'),
        ),
    ]
