# Generated by Django 2.2.2 on 2019-07-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190709_1350'),
        ('users', '0002_auto_20190709_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='member',
            name='birthday_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='member',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watch_list', to='reviews.MovieReview'),
        ),
    ]
