# Generated by Django 2.2.2 on 2019-07-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190709_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterModelOptions(
            name='membergroup',
            options={'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
