# Generated by Django 2.2.3 on 2019-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190919_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmember',
            name='avatar',
            field=models.TextField(default='default.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
