# Generated by Django 2.2.3 on 2019-09-22 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20190919_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 9, 2, 50, 814053)),
        ),
    ]
