# Generated by Django 2.2.3 on 2019-09-22 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0012_auto_20190922_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 12, 2, 4, 278890)),
        ),
    ]
