# Generated by Django 2.2.3 on 2019-07-14 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ReportMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
