# Generated by Django 2.2.3 on 2019-09-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190915_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcomment',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reportreview',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ReportMember',
        ),
    ]
