# Generated by Django 2.2.3 on 2019-09-04 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_moviereview_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='trailer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 4, 17, 15, 25, 121004)),
        ),
    ]
