# Generated by Django 2.2.2 on 2019-07-08 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190708_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 8, 22, 42, 41, 309132)),
        ),
    ]
