# Generated by Django 2.2.2 on 2019-07-09 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190707_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 13, 42, 7, 516159)),
        ),
    ]
