# Generated by Django 2.2.3 on 2019-09-04 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190904_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='cast_producer',
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 4, 18, 13, 28, 724652)),
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
    ]
