# Generated by Django 2.2.2 on 2019-07-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190709_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 9, 13, 50, 32, 280698)),
        ),
    ]
