# Generated by Django 2.2.3 on 2019-09-18 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20190919_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 0, 45, 24, 901278)),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 0, 45, 24, 901278)),
        ),
    ]
