# Generated by Django 2.2.3 on 2019-09-19 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20190919_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmoviereview',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalmoviereview',
            name='review',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='review',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmoviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 9, 2, 35, 559370)),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 19, 9, 2, 35, 559370)),
        ),
    ]
