# Generated by Django 2.2.3 on 2019-09-22 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20190919_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 9, 2, 50, 808056)),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 9, 2, 50, 808056)),
        ),
    ]
