# Generated by Django 2.2.3 on 2019-09-22 11:02

import admin.custom_fields.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_auto_20190922_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoviereview',
            name='genre',
            field=admin.custom_fields.fields.CustomMultiSelectField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Animation'), (4, 'Comedy'), (5, 'Crime'), (6, 'Drama'), (7, 'Fantasy'), (8, 'Historical'), (9, 'Horror'), (10, 'Mystery'), (11, 'Political'), (12, 'Romance'), (13, 'Satire'), (14, 'Sci-Fi')], max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalmoviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 12, 2, 4, 271349)),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='genre',
            field=admin.custom_fields.fields.CustomMultiSelectField(choices=[(1, 'Action'), (2, 'Adventure'), (3, 'Animation'), (4, 'Comedy'), (5, 'Crime'), (6, 'Drama'), (7, 'Fantasy'), (8, 'Historical'), (9, 'Horror'), (10, 'Mystery'), (11, 'Political'), (12, 'Romance'), (13, 'Satire'), (14, 'Sci-Fi')], max_length=32),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 12, 2, 4, 271349)),
        ),
    ]
